// Generated by CoffeeScript 1.6.2
(function() {
  var allowCrossDomain, app, express;

  express = require('express');

  app = express();

  app.use(express.methodOverride());

  allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    if ('OPTIONS' === req.method) {
      return res.send(200);
    } else {
      return next();
    }
  };

  app.use(allowCrossDomain);

  app.use(express["static"](__dirname + '/'));

  app.get('/traffic/between/:from/and/:to', function(req, res, next) {
    return console.log(req);
  });

  app.listen(8080);

}).call(this);
