// Generated by CoffeeScript 1.6.2
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/'));

  app.get('/traffic/between/:from/and/:to', function(req, res, next) {
    return console.log(req);
  });

  app.listen(8080);

}).call(this);
