// Generated by CoffeeScript 1.3.2
(function() {
  var cheerio, request, scrapeTraffic;

  cheerio = require('cheerio');

  request = require('request');

  scrapeTraffic = function(err, resp, html) {
    var $, routePattern, timePattern, ts;
    if (err) {
      return console.error(err);
    }
    ts = Math.round(new Date().getTime() / 1000);
    timePattern = new RegExp(/(\d+)/);
    routePattern = new RegExp(/Minuten[\s\t]+(.*?)$/);
    $ = cheerio.load(html);
    return $('.dir-altroute-inner').each(function(index, value) {
      var route, time;
      time = ($(value)).children('.altroute-aux').text().match(timePattern)[0];
      route = ($(value)).children('div').text().match(routePattern)[1].match(routePattern)[1];
      return console.log(ts + ";" + time + ";" + route);
    });
  };

  request("http://maps.google.de/maps?saddr=Boltzmannstra%C3%9Fe,+Garching&daddr=Theresienwiese,+M%C3%BCnchen&hl=de&ie=UTF8", scrapeTraffic);

}).call(this);
