// Generated by CoffeeScript 1.6.2
(function() {
  var cheerio, from, request, scrapeTraffic, to;

  cheerio = require('cheerio');

  request = require('request');

  if (process.argv.length !== 4) {
    console.error("traffic.js <from> <to>");
    process.exit(1);
  }

  from = process.argv[2];

  to = process.argv[3];

  scrapeTraffic = function(err, resp, html) {
    var $, routePattern, timeHourMinPattern, timeMinPattern, ts;

    if (err) {
      return console.error(err);
    }
    ts = Math.round(new Date().getTime() / 1000);
    timeHourMinPattern = new RegExp(/traffic:[\s\t]+(\d+)[\s\t]+\w+[\s\t]+(\d+)[\s\t]+\w+/);
    timeMinPattern = new RegExp(/traffic:[\s\t]+(\d+)[\s\t]+\w+/);
    routePattern = new RegExp(/Minuten[\s\t]+(.*?)$/);
    $ = cheerio.load(html);
    return $('.dir-altroute-inner').each(function(index, value) {
      var hours, match, mins, route, time, trafficString, trash, _ref;

      _ref = [0, 0], hours = _ref[0], mins = _ref[1];
      trafficString = ($(value)).children('div').slice(1, 2).children('span').text();
      match = trafficString.match(timeHourMinPattern);
      if (match) {
        trash = match[0], hours = match[1], mins = match[2];
      } else {
        match = trafficString.match(timeMinPattern);
        trash = match[0], mins = match[1];
      }
      route = ($(value)).children('div').slice(2, 3).text();
      time = +mins + (+hours * 60);
      return console.log(ts + ";" + from + ";" + to + ";" + time + ";" + route);
    });
  };

  request("http://maps.google.com/maps?saddr=" + encodeURIComponent(from) + "&daddr=" + encodeURIComponent(to) + "&ie=UTF8", scrapeTraffic);

}).call(this);
