// Generated by CoffeeScript 1.6.2
(function() {
  var loadData;

  loadData = function(url, graph) {
    return $.get(url, function(content) {
      var data, data2, entry, from, key, keys, line, mins, minutes, route, routemap, timestamp, to, uniqueKeys, _i, _len, _ref, _ref1;

      data = {};
      _ref = content.split("\n");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        if (line.length < 5) {
          continue;
        }
        _ref1 = line.split(';'), timestamp = _ref1[0], from = _ref1[1], to = _ref1[2], minutes = _ref1[3], route = _ref1[4];
        (data[timestamp] || (data[timestamp] = {}))[route] = minutes;
      }
      data2 = [];
      keys = [];
      for (timestamp in data) {
        routemap = data[timestamp];
        entry = {};
        entry['timestamp'] = timestamp * 1000;
        for (key in routemap) {
          mins = routemap[key];
          entry[key] = mins;
          keys.push(key);
        }
        data2.push(entry);
      }
      uniqueKeys = keys.filter(function(itm, i, a) {
        return i === a.indexOf(itm);
      });
      return new Morris.Line({
        element: graph,
        data: data2,
        xkey: 'timestamp',
        ykeys: uniqueKeys,
        labels: uniqueKeys,
        hideHover: true
      });
    });
  };

  loadData('/traffic_outbound.log', 'traffic_outbound');

  loadData('/traffic_inbound.log', 'traffic_inbound');

}).call(this);
